
// RCA - Root Cause Analysis
// A tree of nodes where each node:
//  - Can have associated metadata
//  - A node can be marked as 'end-of-branch', i.e., will not have any children nodes

export interface RCA_Model {
    id:   number;                 // An unique ID associated with this RCA, generated by the DB
    root: RCA_Node;               // The root node of the RCA analysis tree
}

export enum RCA_NodeType {
    NODE          = 'node',
    END_OF_BRANCH = 'eob'
}

export interface RCA_Node {
    id:     string;              // An unique UUID generated for each node
    title:  string;              // The node title
    type?:  RCA_NodeType;        // The node type

    data?:   Record<string, any>;  // The data associated with this node

    children?: RCA_Node[];        // The ordered list of children for this node. Can be unedefined, i.e., no children for this node

    x: number;
    y: number;
    depth: number;
    maxY: number;
}



